function BW = createDiffMask(RGB, backgroundFrame)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 07-Mar-2023
%------------------------------------------------------
backgroundFrame = im2double(backgroundFrame);
RGB = im2double(RGB);
diff = abs(RGB - backgroundFrame);

% Convert RGB image to chosen color space
I = rgb2hsv(diff);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.000;
channel1Max = 1.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.000;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.073;
channel3Max = 1.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

se = strel("disk",3,0);
BW = imopen(BW,se);

% line によるマスクのクローズ
length = 45.000000;
angle = 10.000000;
se = strel('line', length, angle);
BW = imclose(BW, se);

BW = imfill(BW,"holes");

BW = bwpropfilt(BW,"Area",[1000 Inf]);

se = strel("disk",5,0);
BW = imclose(BW,se);

se = strel('disk', 15, 0);
BW = imopen(BW, se);
BW = imclose(BW, se);

% BW = bwpropfilt(BW,"Area",[3000 Inf]);

end
