function [BW,maskedImage] = segmentImage(X)
%segmentImage イメージの領域分割アプリから自動生成されたコードを使用してイメージをセグメント化
%  [BW,MASKEDIMAGE] = segmentImage(X) イメージの領域分割アプリから自動生成されたコードを使用してイメージ X
%  をセグメント化します。最終セグメンテーションは BW で返され、マスク イメージは MASKEDIMAGE で返されます。

% Auto-generated by imageSegmenter app on 13-Feb-2023
%----------------------------------------------------
X = im2gray(X);

% データ範囲にわたるようにデータを調整します。
X = imadjust(X);

% 空のマスクを作成
BW = false(size(X,1),size(X,2));

% イメージのしきい値処理 - 適応しきい値
BW = imbinarize(im2gray(X), 'adaptive', 'Sensitivity', 0.240000, 'ForegroundPolarity', 'bright');

% 穴の塗りつぶし
BW = imfill(BW, 'holes');

% default によるマスクのオープン
radius = 3;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

