function [BW,maskedImage] = segmentImage154v3(X)
%segmentImage イメージの領域分割アプリから自動生成されたコードを使用してイメージをセグメント化
%  [BW,MASKEDIMAGE] = segmentImage(X) イメージの領域分割アプリから自動生成されたコードを使用してイメージ X
%  をセグメント化します。最終セグメンテーションは BW で返され、マスク イメージは MASKEDIMAGE で返されます。

% Auto-generated by imageSegmenter app on 13-Feb-2023
%----------------------------------------------------
X = im2gray(X);

% 空のマスクを作成
BW = false(size(X,1),size(X,2));

% イメージのしきい値処理 - グローバルしきい値
BW = imbinarize(im2gray(X));

% マスクの反転
BW = imcomplement(BW);

% 穴の塗りつぶし
BW = imfill(BW, 'holes');

% マスクの反転
BW = imcomplement(BW);

% 穴の塗りつぶし
BW = imfill(BW, 'holes');

% マスクの反転
BW = imcomplement(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

